### ISSUE TITLE
Is the lack of error handling intended?

### ISSUE THREAD

**Issue by ghost** [felixhammerl/deps#1]
I just had a glimpse at a few of the installers, and since they don't use `set -e` and finish with `echo ...`, the exit status will always be indicating success.
Also it won't abort on first failure.

If this is intended, please close the issue :).

**Comment by felixhammerl** [comment]
That was intended. `brew` is sometimes brittle when it comes to exit codes, and i didn't invest the time for a proper rollback procedure. i intended to keep it in a way that it will finish up most of the installs that work and clean up the rest later manually. if you have ideas on how to improve that, i'm all ears :)

brewfiles was recently pointed out to me, so maybe that would be a solution here...

**Comment by ghost** [comment]
Good enough :)! Thanks
